#ifndef HEAD_H
#define HEAD_H

#include <QEvent>
#include <QGraphicsScene>
#include <QKeyEvent>
#include <QTime>
#include <QMenu>
#include <QToolBar>
#include <Qaction>
#include <QTableWidgetItem>
#include <QTableWidget>
#include <QScrollArea>
#include <QMenuBar>
#include <QDialog>
#include <QStatusBar>
#include <QMessageBox>
#include <QSqlQuery>
#include <QDateTime>
#include <QPainter>
#include <QGraphicsView>
#include <QCoreApplication>
#include <QDebug>
#include <QtSql/QSqlDatabase>
#include <QStringList>
#include <QObject>
#include <QRectF>
#include <QHostAddress>
#include <QLineEdit>
#include <QPushButton>
#include <QLabel>
#include <qdebug.h>
#include <QHostInfo>
#include <QNetworkInterface>
#include <QProcess>
#include <QMainWindow>
#include <QAction>
#include <QHostAddress>
#include <QMainWindow>
#include <QMediaPlayer>
#include <QMediaPlaylist>
#include <QVideoWidget>
#include <QUrl>
#include <QHeaderView>
#include <QComboBox>
#include <QHostInfo>
#include <QProcess>
#include <QNetworkInterface>
#include <QList>
#include <QTimer>
#include <QGraphicsItem>
#include <QtSql>
#include <QStringList>
#include <QStackedLayout>
#include <QMainWindow>
#include <QPaintEvent>
#include <QTimer>
#include <QImage>
#include <QLatin1String>
#include <QNetworkAccessManager>
#include <QMediaplayer>
#include <QVBoxLayout>
#include <QByteArray>
#include <QList>
#include <QTableWidget>
#include <QEvent>
#include <QGraphicsScene>
#include <QKeyEvent>
#include <QTime>
#include <QMenu>
#include <QToolBar>
#include <Qaction>
#include <QTableWidgetItem>
#include <QTableWidget>
#include <QMenuBar>
#include <QDialog>
#include <QStatusBar>
#include <QMessageBox>
#include <QSqlQuery>
#include <QDateTime>
#include <QPainter>
#include <QGraphicsView>
#include <QCoreApplication>
#include <QDebug>
#include <QtSql/QSqlDatabase>
#include <QStringList>
#include <QObject>
#include <QRectF>
#include <QHostAddress>
#include <qdebug.h>
#include <QHostInfo>
#include <QNetworkInterface>
#include <QProcess>
#include <QMainWindow>
#include <QAction>
#include <QHostAddress>
#include <QHeaderView>
#include <QHostInfo>
#include <QProcess>
#include <QNetworkInterface>
#include <QList>
#include <QTimer>
#include <QGraphicsItem>
#include <QtSql>
#include <QStringList>

#include <QByteArray>
#endif // HEAD_H
